config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq' if Rails.env.development?
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "posts#index"

  resource :profile, only: [:show, :edit, :update]

  resources :posts, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    
    resource :like, only: [:show, :create, :destroy]
    resources :comments, only: [:index, :create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :content, presence: true

  belongs_to :post
  belongs_to :user

  after_create :send_email

  private
  def send_email
    CommentMailer.new_comment(user, content).deliver_later
  end
end

app/models/like.rb
class Like < ApplicationRecord

  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  validates :content, presence: true

  has_many_attached :images
  
  belongs_to :user

  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  has_one_attached :avatar
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, presence: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :profile, dependent: :destroy

  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy

  def prepare_profile
    profile || build_profile
  end

  def hasliked?(post)
    likes.exists?(post_id: post.id)
  end

  def avatar_image
    if profile&.avatar&.attached?
      profile.avatar
    else
      'Ellipse.png'
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    added_attrs = [ :username, :email, :password, :password_confirmation, :avatar ]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
    devise_parameter_sanitizer.permit :sign_in, keys: added_attrs
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    post = Post.find(params[:post_id])
    comments = post.comments
    
    render json: comments, Include: { user: [:profile] }
  end

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.build(comment_params)
    @comment.save!

    render json: @comment, include: { user: [:profile] }
  end

  private
  def comment_params
    params.require(:comment).permit(:content).merge(user_id: current_user.id)
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!

  def show
    post = Post.find(params[:post_id])
    like_status = current_user.hasliked?(post)

    render json: { hasLiked: like_status }
  end

  def create
    post = Post.find(params[:post_id])
    post.likes.create!(user_id: current_user.id)

    render json: { status: 'ok' }
  end

  def destroy
    post = Post.find(params[:post_id])
    like = post.likes.find_by!(user_id: current_user.id)
    like.destroy!

    render json: { status: 'ok'}
  end
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]

  def index
    @posts = Post.all.order(created_at: :desc)
  end

  def show
    @post = Post.find(params[:id])
    @comment = @post.comments.build
    @comments = @post.comments
  end

  def new
    @post = current_user.posts.build
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save!
      redirect_to posts_path, notice: '投稿完了'
    else
      flash.now[:error] = '投稿失敗'
      render :new
    end
  end

  def destroy
    post = current_user.posts.find(params[:id])
    post.destroy!
    redirect_to posts_path, notice: '削除成功'
  end

  private
  def post_params
    params.require(:post).permit(:content, images: [])
  end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

  def show
    @user = current_user
    @profile = current_user.prepare_profile
  end

  def update
    @profile = current_user.prepare_profile
    @profile.id = current_user.id
    @profile.assign_attributes(profile_params)
    if @profile.save
      redirect_to profile_path, notice: '更新完了'
    else
      flash.now[:error] = '更新失敗'
      render :show
    end
  end

  private
  def profile_params
    params.require(:profile).permit(:avatar)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/commons/_images.html.haml
.container
  - if post.images.attached?
    - if post.images.size == 3
      .grid_img
        .grid_img-1#item-a
          = image_tag post.images.first, class: 'img'
        .grid_img-2#item-b
          = image_tag post.images.second, class: 'img'
        .grid_img-3#item-c
          = image_tag post.images.third, class: 'img'
    - elsif post.images.size == 2
      .display-flex
        .display-flex-left
          = image_tag post.images.first, class: 'flex-img'
        .display-flex-right
          = image_tag post.images.second, class: 'flex-img'
    - else
      .image-one-box
        = image_tag post.images.first, class: 'image-first'

app/views/commons/_posts.html.haml
.post_container
  - @posts.each do |post|
    .post#post-show{data:{post_id: post.id}}
      .avatar
        = link_to profile_path do
          = image_tag post.user.avatar_image, class: 'usericon'
      .post_user
        = post.user.username
      .post_time
        %time(datetime='#{post.created_at}')= time_ago_in_words(post.created_at)
      = render '/commons/images', post: post

      .delete
        - if user_signed_in? && current_user.id == post.user_id
          = link_to '削除する', post_path(post.id), data:{method: 'delete', confirm: '本当に削除してもよろしいでしょうか？'}

      .icon_container
        .like 
          - if user_signed_in?
            - if current_user.hasliked?(post)
              .post_heart.active-heart{class: '#{post.id}', id: '#{post.id}'}
                = image_tag('heart-active.svg')
              .post_heart.hidden.inactive-heart{class: '#{post.id}', id: '#{post.id}'}
                = image_tag('heart.svg')
            - else
              .post_heart.inactive-heart{class: '#{post.id}', id: '#{post.id}'}
                = image_tag('heart.svg')
              .post_heart.hidden.active-heart{class: '#{post.id}', id: '#{post.id}'}
                = image_tag('heart-active.svg')
        .comment 
          = link_to image_tag('Vector.png'), post_path(post.id), class: 'icon_button'
                
=javascript_pack_tag 'post'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title InstagramCloneApp
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/posts/index.html.haml
.container
  .post_header
    - if user_signed_in? 
      = link_to image_tag('photo-camera (1).png'), new_post_path, class: 'camera_icon'
      = link_to 'ログアウト', destroy_user_session_path, method: :delete, class: 'devise_link link_login'
    - else 
      = link_to 'ログイン', new_user_session_path, class: 'devise_link link_login'
  .timeline_title
    %p ALL POSTS
  .timeline_container
    = render 'commons/posts'

app/views/posts/new.html.haml
.container
  = form_with model: @post do |f|
    .post_new_header
      %div
        %p.status_button STATUS 
      %div
        = f.submit 'POST', class: 'post_new_button'
    .usericon
      = image_tag current_user.avatar_image
    .post_username
      %p= current_user.username
    %div
      = f.text_field :content, placeholder: "What's on your mind ?", class: 'post_content_form'
    %div
      = label :images, '+ Album', class: 'images_input_btn' do
        %i.images_form_name + Album
        = f.file_field :images, multiple: true, class: 'images_form'

     

app/views/posts/show.html.haml
.container#post-show{data:{post_id: @post.id}}
  .comment
    .comments-container
  
  .comment-set 
    .comment-text-area
      = text_area_tag :comment_content, '', class: 'sm'
      .btn-secondary.add-comment-btn
        Add Comment
      

= javascript_pack_tag 'post'

app/views/profiles/edit.html.haml
= form_with(model: @profile, url: profile_path, method: 'put', local: true ) do |f|
  %div 
    = f.file_field :avatar
  %div 
    = f.submit 'SUBMIT', class: 'btn btn-outline-secondary'

app/views/profiles/show.html.haml
.container 
  .profile_header
    .profile_back_icon
      = link_to image_tag('back.svg'), :back 
    .profile_username
      = current_user.username 

  .avatar
    - if current_user.profile&.avatar&.attached?
      = image_tag @user.profile.avatar, class: 'profile_usericon'
    - else
      = image_tag 'Ellipse.png', class: 'profile_usericon'

  .avatar_edit_form.hidden
    = form_with(model: @profile, url: profile_path, method: 'put', local: true ) do |f|
      %div
        = f.label :avatar, '画像選択', class: 'avatar_form' do
          %i.images_form_avatar Select your avatar 
          = f.file_field :avatar, class: 'images_form'      
      %div 
        = f.submit 'SUBMIT', class: 'avatar_submit_btn'

=javascript_pack_tag 'profile'